language: python
python:
- '3.6'
- '3.7'
- '3.8'
branches:
  only:
  - master
install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda env create -q python=$TRAVIS_PYTHON_VERSION -f environment.yml
- source activate goodman_focus
- python setup.py test
- python setup.py install
script:
- coverage run --branch --source= setup.py test
after_success:
- coveralls
notifications:
  slack:
    secure: nJCEgN2ou41cgpRZ89GVBkNbKsxaMaIYVClJcOoU/hTFI3/XLLxsWSe1x+Shp6relrdS/P+T1gwSwvGqKrZWBZ/TDRSAwCyLxZ4l49sfNV7JoHmEgyg4qulXKkPwLpCK7R3PJwE0MAIaZAaklNcxTKV63KjjAXiFuyF3ldK2sjQMwjUeqlomRG+3EZQJUxkQTKAnrupq5gPO+iZlI2jevTYm1qwmT6KhUeg0wQMT49PkA1AZbDK9ch2NysIYAQgEW6nyot7k30rytU3rFetCcrmuzuT7i33LCsjQd/ltyOnnqujVMNE5nFRJLA0k16IV6zZbpIIKhfUb2k3ObtJW8A2lhULF+s4N8ayPl5hZJPZ6c9riLDm96iqLIfi79s09UL3Ws4vN3oTWOgbd/28fNgwl4yqZecuYFT9EUPidTkgYg2P1Pi0r0InsAP+KbELTeQoN+XltBS0sJnoCKkIK/fe1ZZHVXEVkUMt5AqPcv6+UMSS49OjU0+bIkqXlqamlFHWIstcWPVdshNHu9aWqxMtWrYQdhkZDjBbfM9BG9Bv0K8zfNi5n4UyJslmUY6vZl7x+gx5xU7tgZYVmZSckBu1n14PZC8lGQHuuuP4poLlQ954Q+TB7Jwv177apR20Vx6DKw/od7i6Zy2MwxbUhFtn8V7oa8wLSQYInnUXlL4I=
