name: goodman_focus
channels:
  - astroconda
dependencies:
  - astropy
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - pip:
      - ccdproc
      - coveralls
      - m2r
      - sphinx
      - sphinxcontrib.napoleon
